[solution]
name = "gdn-solution-v1"      # Solution name
definition = "gdn_prefill_qk4_v8_d128_k_last"          # Track: fused_moe | sparse_attention | gated_delta_net
author = "Saman Keon"              # Team/author name

[build]
language = "python"               # triton | cuda
entry_point = "kernel.py::cuteGDN"            # Kernel function name
